### ISSUE TITLE
Random color selection

### ISSUE THREAD

**Issue by itayganor** [catdad/canvas-confetti#128]
Hi,

First of all, I have to say - This library is amazing! It is just what I was looking for, coming from Unity (did I just compared this to Unity's particle engine? I'd call that a compliment).

I have a question - 
In the "School Pride" demo you fire two color options, which looks awesome; But as soon as you try to add a third color to the array, the fired confetti are only red and white.

`const colors = ['#bb0000', '#ffffff', '#bada55'];`

![image](https://user-images.githubusercontent.com/6430313/96378246-4b87fc80-1193-11eb-831b-edef3587d521.png)

I think it happens because `particleCount` is limited to two, and the colors are picked in order from the array.

I think the easiest way to allow multiple color options while limiting the particleCount, is to have an option to choose a random color when firing a confetti. This will make sure all colors are used.

What do you think?

**Comment by catdad** [comment]
I actually did think about this. I ran into a similar situation trying to make some advanced effects. Since this is limited to situations where you have more colors than confetti particles (which I think is rare, since there are a small amount of unique colors that look good together, and also not many cases where you want a very small number of particles). Anyway, in the cases where this matters, you might want one of two things:
* just any of these colors at random is fine, as long as they all get used at some point
* an exact and predictable algorithm that allows me to do what I want

Those are of course exact opposites and I had to pick mostly just one. Of course, every case does have a workaround too:
* when colors are chosen at random, always only pass in one color -- effectively, you can use `parcleCount: 1` and only a single color, and get completely control over the algorithm that way, albeit with a lot of code
* when colors are chosen in order, you can either use more confetti (at a longer interval), or manually assign a single color to each round of launching confetti

Effectively, I had to pick one option and make the other a bit more difficult. I decided that it is easier to do "random" when you have a predictable algorithm rather than do predictable when you have a random algorithm.

You can easily adapt that demo to do 3 colors (or an arbitrary amount of colors) like this:

```javascript
var end = Date.now() + (15 * 1000);

var colors = ['#bb0000', '#ffffff', '#bada55', '#ff00ff'];
var count = 0;

(function frame() {
  var color = colors[count++ % colors.length];
  
  confetti({
    particleCount: 2,
    angle: 60,
    spread: 55,
    origin: { x: 0 },
    colors: [color]
  });
  confetti({
    particleCount: 2,
    angle: 120,
    spread: 55,
    origin: { x: 1 },
    colors: [color]
  });

  if (Date.now() < end) {
    requestAnimationFrame(frame);
  }
}());
```

![image](https://user-images.githubusercontent.com/2205537/96515198-e84da700-1232-11eb-898b-c1ff9fd7f578.png)

Now... supporting both cases (i.e. adding a `randomColorOrder: true` kind of option) could be fine, but I prefer not to complicate the API if there isn't a really good case for it.
