### ISSUE TITLE
Do you have plans to write a react component?

### ISSUE THREAD

**Issue by ulitcos** [catdad/canvas-confetti#138]

**Comment by catdad** [comment]
I have thought about this a bit, and the short answer is not really.

Here's the long answer: I don't quite see the benefit that a React component would provide, or what behavior would even be expected. Would it just launch confetti on mount based on props? Would it cleanup implicitly or need an API to cleanup? What is the expectation when using multiple instances of the component? Should it be a context instead? How would you launch more confetti (i.e. things like the snow demo)? Would you constantly need to trigger state changes?

All of this amount to shipping more code in order to have a far more limiting experience, and would certainly introduce extra overhead by having to deal with React's state and re-rendering.

**Comment by ulitcos** [comment]
Thank you for your detailed response. I have a clear understanding of what I want from the implementation of the component on react. I have already written a simple implementation locally in my project, but I already have plans to use it in other projects and I want more flexibility. If you don't mind, I would implement the component on react and publish it as a separate package?

**Comment by catdad** [comment]
Sorry for the delay. You obviously should feel free to implement anything you would like with this module! Yay open source! Feel free to tag me if you make anything awesome that you want to show off, I am always happy to see my projects being used!

**Comment by robinmetral** [comment]
For the record: https://github.com/ulitcos/react-canvas-confetti (thanks @ulitcos)

**Comment by abernier** [comment]
I've written a step-by-step article on transposing this library to a React component: https://github.com/abernier/abernier/blob/main/articles/vanilla2react.md
