### ISSUE TITLE
The confetti does not show in fullscreen mode

### ISSUE THREAD

**Issue by deepansh96** [catdad/canvas-confetti#159]
I have a video player, and I'm trying to show modals on top of that video player. Whenever a modal appears on the video, the confetti gun fires.

This all works fine when NOT in fullscreen mode. As soon as the confetti gun fires, if I go into fullscreen mode, I can't see any confetti. As soon as I exit fullscreen, I can see them being rendered.

The canvas element that is being used to draw has `resize: true` and has the highest z-index.

Please help me out

**Comment by catdad** [comment]
Do you have something that reproduces this issue that I can look at?

**Comment by deepansh96** [comment]
Hey, sorry for the late reply. I've created a bare-bones codepen to demonstrate the issue. It's totally possible that this is not a bug but a lack of implementation from my end. 

https://codepen.io/deepansh96/pen/ExXrbdO

To replicate - 
- Whenever the player is paused, some confetti are animated onto a canvas element
- However, if the video is in fullscreen, and then the video is paused, I cannot see the confetti
- What's weird is when I exit fullscreen, you can see that the drawing of confetti had already begun, it just wasn't showing when player was in fullscreen

**Comment by catdad** [comment]
So the thing about fullscreen is that a particular element gets set to fullscreen, with all other elements being hidden. That's basically the entire point of fullscreen.

@deepansh96 in your codepen, the element being made fullscreen is the video itself. The confetti canvas is a separate element not inside the video. Therefore, only the video is shown, with all other elements (including the canvas) being hidden. That is how fullscreen is supposed to work.

In order to show the video and the confetti, both the video player and the canvas element need to be places inside the same parent element, and then that parent element can be made fullscreen using the [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). I [updated your codepen here](https://codepen.io/catdad/pen/VwzvqKw) to show that working. There are, of course, a lot of usability issues in my example, but it was meant to be a quick example of a solution rather than a final user-friendly implementation.

**Comment by catdad** [comment]
@ocarreterom Unfortunately, I do not have access to an Android TV or the Odin browser. This may be related to the issue above or it may be entirely separate. If you don't believe the issue described above it at fault, please file a separate but with additional information.

**Comment by ocarreterom** [comment]
Thanks @catdad , it's working with a custom canvas 👍
