### ISSUE TITLE
Enable `prefers-reduced-motion` by default

### ISSUE THREAD

**Issue by petercr** [catdad/canvas-confetti#176]
I wanted to go ahead and voice my opinion that you should change the default behavior of `canvas-confetti` to use reduced motion by default, and leave developers the option to opt out of it. 

Similar to the way it works now, except you would have to opt out of `prefers-reduced-motion` instead of into it. 

I know that when you look at the original [CSSWG spec]([Media Queries Level 5 (csswg.org)](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-motion)) on this one, it reads like this:

> Indicates that user has notified the system that they prefer an interface that removes or replaces the types of motion-based animation that either trigger discomfort for those with vestibular motion sensitivity, or distraction for those with attention deficits.

I originally thought that this issue did not seem like a big deal, as that is kind of how the spec reads. Personally I _**have ADD**_, and still I didn't put much thought into it.

However, in the last year or so I have seen other developers who I respect on Twitter talking about how this particular issue effects **them and their disability. 

It turns out that substantial motion and/or animations can make some people nauseous, and give them vertigo for up to an entire day. 
**Even worse it could actually make them 🤮!**  

I feel as developers we should try our best to not make people sick, if at all possible 👌🏻
And that is why I am opening this issue.

Most of us will never even notice the difference, but I believe it is important to respect the people who do need this.

Thank you and congrats on this awesome project 🥳🎊

**Comment by catdad** [comment]
Thank you for your input. I do appreciate your thorough writeup.

I do want to clarify: [my initial decision](https://github.com/catdad/canvas-confetti/issues/114) was not based on me interpreting the mild language to mean that the issue is a mild one. I am well aware that this can be a serious issue for some folks. My decision was based on another portion of the spec which you did not copy:

> The `prefers-reduced-motion` media feature is used to detect if the user has requested the system minimize the amount of non-essential motion it uses.

Specifically, the "non-essential motion" wording. The one and only purpose of this module is to animate confetti. That is to say, animation is an "essential motion" when it comes to this library. What you are talking about is how the library is used. If I can metaphor, this would be similar to asking a lights manufacturer if they could solve the problem of flashing lights at concerts due to light sensitivity issues of some patrons.

I don't know [how or why](https://github.com/catdad/canvas-confetti/issues/114#issuecomment-608431191) this library is being used, and I cannot make the decision for whether it is essential or non-essential for another developer's application.

I am not sure your post has added anything new to this dialog. I do appreciate your input though, and will certainly consider this as a +1 in that direction.

**Comment by petercr** [comment]
Thanks so much for getting back to me with such a well detailed explanation as to why and how you came to your decision.
It is much appreciated 👍 

Yeah, _**I totally missed**_ issue #114 when I putting together mine. 
Sorry about that 😅, my bad. 
I didn't understand why it wasn't on by default, and now I do. 

Thanks for considering my take on this.
I'm going to go ahead and close this issue, since it's taken care of.

Thanks again 👋
