### ISSUE TITLE
Better offset values

### ISSUE THREAD

**Issue by MichalKrakow** [catdad/canvas-confetti#187]
Lets jus say there's planty space for improvement. Making a simple thing: confetti at cursor poistion is unnecessary painfull. 
Mayby accept units as px, or % would be an good idea?

**Comment by catdad** [comment]
Sorry, I am not sure what you mean. Can you elaborate? I can't tell what this is issue is asking for.

**Comment by leettaylor** [comment]
@catdad I believe what @MichalKrakow is referring too is this:

Firing confetti at cursor position on click:

```js
// How it is:
document.addEventListener("click", (event) => {
    confetti({
        origin: {
            x: event.clientX / window.innerWidth,
            y: event.clientY / window.innerHeight,
        },
    });
});

// How it could be made easier:
document.addEventListener("click", (event) => {
    confetti({
        origin: {
            x: `${event.clientX}px`,
            y: `${event.clientY}px`,
        },
    });
});
```

**Comment by catdad** [comment]
I am not sure I agree that the second example is **easier** than the first. Maybe you mean that it is easier for a user to understand this simple case? Maybe, but the percentage also seem fairly easy. On the other hand, pixel values would make it difficult to implement on a page that is used across multiple different screen sizes. Further, creating a string and parsing values out of that string introduce unnecessary performance, it would have to be **a lot easier** to understand in order to implement that.

"Confetti at cursor" is currently possible, and as demonstrated, pretty easy to do.  I am closing this issue.
