### ISSUE TITLE
Add Confetti Title Text 

### ISSUE THREAD

**Issue by adamwreuben** [catdad/canvas-confetti#201]

**Comment by Rahulkottak** [comment]
Bro what type of issue is this!?.. at least describe your issue properly or attach any screenshot about the issue

**Comment by saurabhbakolia** [comment]
> attach

![image](https://github.com/catdad/canvas-confetti/assets/78996216/b0aed946-51b8-4034-adcb-7949d29db9b6)

The title is not in the canvas-confetti demo website, I would like to work on it.

**Comment by Rahulkottak** [comment]
I too would like to contribute on this issue.. if @catdad would allow

**Comment by Hitmanmtata** [comment]
> > attach
> 
> ![image](https://user-images.githubusercontent.com/78996216/271178663-b0aed946-51b8-4034-adcb-7949d29db9b6.png)
> 
> The title is not on the canvas-confetti demo website, I would like to work on it.

Okay...Am sorry it wasn't supposed to be an issue...I just wanted to be a feature for example this image below


![configet_titile_sample](https://github.com/catdad/canvas-confetti/assets/124803905/bad72b35-a28b-4aff-984e-8f3b3a3af79c)

Let's say the cup is the confetti.. but on top of it. there is a text that says GHS 39,000.
So I wanted u guys to add that Title text as one of the properties. Like when the confetti displays then we can show the text on top of it for certain font size, colors etc

**Comment by saurabhbakolia** [comment]
> Title text as one of the propertie

So, do you want to add a image of related content and that image text needs to be static right ??
If it is so, I would like to work on it.

**Comment by adamwreuben** [comment]
> > Title text as one of the proper
> 
> So, do you want to add an image of related content and that image text needs to be static right ?? If it is so, I would like to work on it.

Yes like, when the confetti is displaying, it could show like a big Text that Congratulations. something like that.

**Comment by saurabhbakolia** [comment]
ok. Then I would like to work on it. assign it to me

**Comment by adamwreuben** [comment]
@catdad Kindly Assign this task to him. Thank You

**Comment by adamwreuben** [comment]
> ok. Then I would like to work on it. assign it to me

@catdad

**Comment by saurabhbakolia** [comment]
@adamwreuben  Checkout this change. If it's ok then I am committing my changes. 
![Canvas Confetti Page Title Issue](https://github.com/catdad/canvas-confetti/assets/78996216/467c1e67-59f1-48a7-ac29-6cb209d25ce0)


Page title will change to this ( 🎉 Congratulations ) when button is clicked and after some seconds it will set back to (🎉 | Canvas Confetti).

**Comment by Hitmanmtata** [comment]
<img width="1092" alt="Screen Shot 2023-10-03 at 09 56 10" src="https://github.com/catdad/canvas-confetti/assets/124803905/55a14e4d-2032-46a9-9b08-f6faf4ce8f37">
I didnt mean it that title on. that bar


I. meant the text should appear. on top of confetti like this below
<img width="857" alt="Screen Shot 2023-10-03 at 09 58 36" src="https://githu
<img width="861" alt="Screen Shot 2023-10-03 at 09 58 49" src="https://github.com/catdad/canvas-confetti/assets/124803905/b7b5bbb7-f311-4589-b99b-2e0d55a5b335">
b.com/catdad/canvas-confetti/assets/124803905/a6b38329-7202-4cd6-9075-0cc379eb
<img width="781" alt="Screen Shot 2023-10-03 at 09 59 05" src="https://github.com/catdad/canvas-confetti/assets/124803905/8abb7ffc-6f5a-42b9-b402-6a34b20f2599">
00d5">

I hope u got a point

**Comment by catdad** [comment]
Okay... this issue has gotten a bit out of hand.

The original author didn't describe anything, and has not contributed further to the discussion. So as written, the original issue should be closed as `invalid`.

One user suggested that the demo site has no HTML title. And... it's a demo site, and a title really serves no purpose in demonstrating the library. Either way, I added a title anyway already. That discussion seems to be a distraction really.

Another user mentioned wanting this confetti library to also populate arbitrary text on the page as well. That is not a problem that needs to be solved. Web pages and applications are already very well suited for displaying text, and text is not an inherent part of confetti. It is out of scope of this library, and there are countless reasons why it would be a bad idea for text to be rendered by this library as an image rather than by the web page/application as actual text. I am not seeing any compelling reason for static text to be added to this library. As such, that topic should be closed as `invalid` as well.

In all cases, I am closing this issue. No work should be done here.

**Comment by Hitmanmtata** [comment]
@catdad I didn't say render text as an image, those pictures above are examples. If that seems to u an invalid feature. Alright!
