### ISSUE TITLE
Emoji confetti broken on iOS Safari

### ISSUE THREAD

**Issue by avmdstudent** [catdad/canvas-confetti#209]
Thank you so much for creating and maintaining this package, the effects are beautiful and performant on all platforms tested 🎉

It seems that the new emoji confetti feature is broken on iOS Safari (tested on iOS 17 iPhone SE 2022). The emoji confetti effect will not render on iOS devices. Attempting to create the emoji confetti will also freeze any confetti already drawn on the canvas (the suspended particles only go away after a page refresh). I was able to reproduce this on my own app as well as the demo (https://www.kirilv.com/canvas-confetti/). Is there something about the ios emoji font that causes this behavior?

**Comment by catdad** [comment]
Huh, that is so weird. I tested it when I was developing this feature on iOS 16 and it was working great. My iPad is on iOS 17 now and sure enough, exactly what you described happens. What's even weirder is that I don't see anything in the console either. I'll definitely be taking a look at this this week when I have some more time.

**Comment by catdad** [comment]
I guess I must have checked some intermediary state on my iPad, because sure enough, Safari does not support creating a canvas pattern using `ImageBitmap`, and it seems they have not supported it for quite a while:
* https://bugs.webkit.org/show_bug.cgi?id=149986
* https://stackoverflow.com/questions/75556912/createpattern-doesnt-work-with-imagebitmap-in-safari

I am looking for a workaround for iOS

**Comment by catdad** [comment]
A fix for this has been released in version 1.9.1.
