### ISSUE TITLE
consider adding more shapes, btw the code editor in demo page is buggy

### ISSUE THREAD

**Issue by zzz6519003** [catdad/canvas-confetti#227]

**Comment by catdad** [comment]
Since [`shapeFromPath`](https://github.com/catdad/canvas-confetti?tab=readme-ov-file#confettishapefrompath-path-matrix---shape) (and also [`shapeFromText` a.k.a. emoji](https://github.com/catdad/canvas-confetti?tab=readme-ov-file#confettishapefromtext-text-scalar-color-fontfamily---shape)) exist, I will no longer be adding any more shapes. You can easily add any shape you could imagine as an SVG path.

If you have specific bugs to report, please open issues for them. "Buggy" is not really something I can address.
