### ISSUE TITLE
Extra property/css on canvas

### ISSUE THREAD

**Issue by showenx** [catdad/canvas-confetti#69]
This is a feature request regarding the **options**, it would be good if we can include some extra property or class in the options, so it would be easier to refer them later on or style them.

**Comment by showenx** [comment]
maybe something like this:
```
confetti.create()({
        shapes: ['square'],
        particleCount: 200,
        spread: 50,
        angle: 45,
        class: 'custom-wide'
      });
```

**Comment by catdad** [comment]
Can you clarify what you are asking for? I am not sure what use case you are suggesting.

**Comment by showenx** [comment]
so in the code we have 
```
onfetti.create()({
        shapes: ['square'],
        particleCount: 200,
        spread: 50,
        angle: 45,
        class: 'custom-wide'
      });
``` 

in the result we have
```
<canvas width="1680" height="360" class="custom-wide" style="position: fixed; top: 0px; left: 0px; pointer-events: none;"></canvas>
```

**Comment by catdad** [comment]
I am still not following exactly. Do you want `confetti` to create a new canvas each time and apply your class to it? Do you want to provide your own canvas instead of using the one that `confetti` creates?

In either case, you can already accomplish this type of functionality yourself. [There is already an option to provide your own canvas](https://github.com/catdad/canvas-confetti#confetticreatecanvas-globaloptions--function). The code would look something like this:

```javascript
// get already existing canvas
var myCanvas = document.querySelector('custom-wide');

// OR create a new one
var myCanvas = document.createElement('canvas');
myCanvas.className = 'custom-wide';
document.body.appendChild(myCanvas);

// use the canvas you created in one of the two previous steps
confetti.create(myCanvas, { resize: true })({
  shapes: ['square'],
  particleCount: 200,
  spread: 50,
  angle: 45
});
```

**Comment by showenx** [comment]
understand we can manually create a canvas, and apply the confetti , but if would be really handy if we can just include one property and save all these code

```
// get already existing canvas
var myCanvas = document.querySelector('custom-wide');

// OR create a new one
var myCanvas = document.createElement('canvas');
myCanvas.className = 'custom-wide';
document.body.appendChild(myCanvas);
```

**Comment by catdad** [comment]
The are two problems with doing that though:
1. This library would do two things instead of one thing. It would do confetti, but it would also manage DOM elements for you. I don't like libraries that do two things.
2. This kind of update would save you from writing 1 or 3 lines of code, but would mean that everyone using the library now has to have that code whether they want it or not. Putting application concerns in an unrelated library is generally not a good practice.

Am I just missing the benefit? I want to do what is best for my users, but all you have said so far is "it's handy".

**Comment by adamreisnz** [comment]
I think probably what he was after is just the ability to use the canvas that the library creates/provides, but have some kind of ability to style it easily, by allowing you to specify a custom class that gets appended to the canvas that the library creates. No dom management, just a classname.

**Comment by adamreisnz** [comment]
Currently, there is no way to target the element that this library creates, so at the very least it would be nice/handy/useful and save us time if the library could add a (default) class to the element, something like `canvas-confetti`. That way we don't have to create elements ourselves and worry about their positioning and DOM management, because we can simply add one css rule to target the default class.

**Comment by showenx** [comment]
> Currently, there is no way to target the element that this library creates, so at the very least it would be nice/handy/useful and save us time if the library could add a (default) class to the element, something like `canvas-confetti`. That way we don't have to create elements ourselves and worry about their positioning and DOM management, because we can simply add one css rule to target the default class.
> 
> I think adding a simple class name to the element won't add bloat to the library, and it will make it easier for people wanting to add some custom styling to the canvas.

exactly, custom class would be ideal, but a "(default) class" should do the job.

**Comment by catdad** [comment]
Styling a canvas is not a trivial task that you can just do (I explain this in the README in more depth, but a canvas has the drawing size as well as an element size, and only the element size is controlled by CSS). Changing the CSS can also cause support issues in the future as this library changes. The issue is not about bloat, but about overhead in supporting a library (e.g. unexpectedly breaking other people's code, answer questions about why applying CSS makes the library behave in unexpected ways, etc.). That is why there is such a clear line between the automatic canvas and using a custom canvas that you have control over.

Perhaps if creating a canvas so that you can position it as you like is too hard and time consuming, perhaps we can work on improving the code example to make it easier?

**Comment by adamreisnz** [comment]
I found my needs were met with the `zIndex` configuration property.

**Comment by cusxio** [comment]
Is it possible to have add the option to add a class name on the canvas? So that I can easily unmount the canvas on page change.
